# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 42c0808ddc870073613304475b05fe6303577304600aac2688451268ae978fcc7d7b68361e25530077331fc7f672e1926daf5907a2ebe202718ba563722018a4

test:
  secret_key_base: 7ce129ab2f2ef4d0d66159bdab9c057bb118831fae09f420e74465c0fc8c63055de93a05c3b08a582409de19f5359ae7ea2790c1b9e381eb93fbc68ca15e76b0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
